# Generated by Django 4.1 on 2022-08-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0002_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
