# Generated by Django 4.1 on 2022-08-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0002_movie_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
