# Generated by Django 4.1 on 2022-08-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0003_remove_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='movie_library.actor')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actors', to='movie_library.movie')),
            ],
            options={
                'db_table': 'movie_actor',
            },
        ),
    ]
