# Generated by Django 4.1 on 2022-08-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('movies', models.ManyToManyField(to='movie_library.movie')),
            ],
            options={
                'db_table': 'actor',
            },
        ),
    ]
