# Generated by Django 4.1 on 2022-08-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0004_movieactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='movie_library.MovieActor', to='movie_library.actor'),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_library.movie'),
        ),
    ]
