# Generated by Django 4.1 on 2022-08-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0005_movie_actors_alter_movieactor_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='actors', to='movie_library.movie'),
        ),
    ]
