# Generated by Django 4.1 on 2022-08-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0005_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Other')], default='Female', max_length=6),
        ),
    ]
