# Generated by Django 4.1 on 2022-08-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0006_actor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, db_index=True, unique=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_library.movie')),
            ],
        ),
    ]
