# Generated by Django 4.1 on 2022-08-30 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0006_remove_movie_actors_alter_movieactor_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='movie_library.MovieActor', to='movie_library.movie'),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='actors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_library.actor'),
        ),
    ]
