# Generated by Django 4.1 on 2022-08-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0007_actor_movies_alter_movieactor_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='actors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_library.actor'),
        ),
        migrations.AlterField(
            model_name='movieactor',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='movie_library.movie'),
        ),
    ]
