# Generated by Django 4.1 on 2022-08-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0007_trailor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trailor',
            new_name='Trailer',
        ),
    ]
