# Generated by Django 4.1 on 2022-08-18 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0008_rename_trailor_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.CreateModel(
            name='Actor_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_library.actor')),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie_library.movie')),
            ],
            options={
                'db_table': 'actor_movie',
            },
        ),
    ]
