# Generated by Django 4.1 on 2022-08-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0009_remove_actor_movies_actor_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_image',
        ),
    ]
