# Generated by Django 4.1 on 2022-09-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0009_usermovies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uploaded_image', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
