# Generated by Django 4.1 on 2022-08-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0010_remove_movie_cover_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
    ]
