# Generated by Django 4.1 on 2022-08-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0011_alter_movie_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
    ]
