# Generated by Django 4.1 on 2022-09-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0011_alter_image_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_image',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
