# Generated by Django 4.1 on 2022-09-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0012_alter_image_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movie_library.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.IntegerField(choices=[(1, 'Cover'), (2, 'Other')], default=2),
        ),
    ]
