# Generated by Django 4.1 on 2022-08-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0013_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movie_library.actor'),
        ),
        migrations.DeleteModel(
            name='Actor_Movie',
        ),
    ]
