# Generated by Django 4.1 on 2022-08-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0014_movie_actors_delete_actor_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='created',
            field=models.DateTimeField(default='2022-08-22 06:24:47.335658+00:00'),
        ),
        migrations.AddField(
            model_name='actor',
            name='updated',
            field=models.DateTimeField(default='2022-08-22 06:24:47.335658+00:00'),
        ),
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default='2022-08-22 06:24:47.335658+00:00'),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated',
            field=models.DateTimeField(default='2022-08-22 06:24:47.335658+00:00'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='created',
            field=models.DateTimeField(default='2022-08-22 06:24:47.335658+00:00'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='updated',
            field=models.DateTimeField(default='2022-08-22 06:24:47.335658+00:00'),
        ),
    ]
