# Generated by Django 4.1 on 2022-08-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0015_actor_created_actor_updated_movie_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
