# Generated by Django 4.1 on 2022-08-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0016_alter_actor_created_alter_actor_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='movie',
        ),
        migrations.AddField(
            model_name='trailer',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Trailer', to='movie_library.movie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),

    ]
