# Generated by Django 4.1 on 2022-08-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0017_remove_trailer_movie_trailer_movies_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trailer',
            table='trailer',
        ),
    ]
