# Generated by Django 4.1 on 2022-08-23 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0018_alter_trailer_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trailer',
        ),
    ]
