# Generated by Django 4.1 on 2022-08-23 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0019_delete_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, db_index=True, unique=True)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trailer', to='movie_library.movie')),
            ],
            options={
                'db_table': 'trailer',
            },
        ),
    ]
