# Generated by Django 4.1 on 2022-08-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0020_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='movies',
        ),
    ]
