# Generated by Django 4.1 on 2022-08-23 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0021_remove_trailer_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Trailer', to='movie_library.movie'),
            preserve_default=False,
        ),
    ]
